version: '3'

services:
  nginx:
    container_name: laravel-nginx
    image: nginx:1.20.2
    restart: always
    volumes:
      - ./backend-core:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/templates
    depends_on:
      - php
    links:
      - php
    ports:
      - "${COMPOSE_NGINX_PORT}:80"

  php:
    container_name: laravel-php
    build:
      context: ./docker/images/php
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./backend-core:/var/www/html
      - ./docker/images/php/pool.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/images/php/supervisor:/etc/supervisor/conf.d
    links:
      - postgres
  postgres:
    container_name: laravel-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${DB_DATABASE}"
      POSTGRES_PASSWORD: "${DB_ROOT_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    ports:
      - "${COMPOSE_POSTGRES_PORT}:5432"
    volumes:
      - ./docker/db:/var/lib/postgresql/data